name: build and push go lang

on:
  push:
    branches: [ main ]

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: "build"
    uses: vishalmamidi/workflows/.github/workflows/build-golang.yml@main
